### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Tarasovych**

### CODE REVIEW

**Comment by Tarasovych** [comment]
@carrodher if you are using https://github.com/BonnierNews/logstash_exporter as the base, than `-exporter.bind_address` must be valid. You can try to run something like this
```yaml
version: '3.7'

services:
  logstash_exporter:
    image: bitnami/logstash-exporter:0.1.2
    command:
      - '--exporter.bind_address=:9198'
```
and you'll get an error.

**Comment by carrodher** [comment]
It seems the README is not updated, in the go code both repos are using the same flag:
```go
func main() {
	var (
		logstashEndpoint    = kingpin.Flag("logstash.endpoint", "The protocol, host and port on which logstash metrics API listens").Default("http://localhost:9600").String()
		exporterBindAddress = kingpin.Flag("web.listen-address", "Address on which to expose metrics and web interface.").Default(":9198").String()
	)
```
this is an example from [BonnierNews/logstash_exporter](https://github.com/BonnierNews/logstash_exporter/blob/d0391964df9c3ba49a605c0c7d98399b0e54e586/logstash_exporter.go#L106) but sequra/logstash_exporter it using the same parameter. So I think the README in the first one is not up-to-date.

I am going to create an internal task to revisit this topic and use sequra/logstash_exporter if BonnierNews/logstash_exporter is not receiving updates, but at this moment we are using this one. The error you are describing is due to a lack of updating the docs.

**Comment by oxyrox** [comment]
@carrodher Has there been any update on this topic? [BonnierNews](https://github.com/BonnierNews/logstash_exporter) seems to be dead and [sequra/logstash_exporter](https://github.com/sequra/logstash_exporter) seems to be the most up-to-date fork.
Are there still plans to migrate the bitnami docker image to use sequras version of the logstash exporter?

**Comment by carrodher** [comment]
The task is still on our backlog as we are a small team dealing with different things. What is your specific use case? Is there any missing feature that is already implemented in the sequra one?

**Comment by carrodher** [comment]
Hi, we released some weeks ago a new branch (7.3) based on the sequra source code. Feel free to provide any feedback

**Pull request closed without merging**
